function cmd = buildCSTCurve(X,Y,Z,name)

cmd = '';

cmd = [cmd ...
    'With Polygon3D' newline ...
    '    .Reset' newline];

cmd = [cmd ...
    sprintf('    .Name "%s"\n',name)];

cmd = [cmd ...
    '    .Curve "Curve1"' newline];

for n = 1:length(X)

    cmd = [cmd ...
        sprintf( ...
        '    .Point "%f", "%f", "%f"\n', ...
        X(n), ...
        Y(n), ...
        Z)];
end

cmd = [cmd ...
    '    .Create' newline ...
    'End With' newline newline];