function geom = buildMetamaterial(params)

geom = {};

if strcmp(params.type,'gielis')

    if params.spacing <= params.thickness

        params.spacing = ...
            params.thickness + 0.05;
    end

    base_radius = params.a;

    for rIdx = 0:(params.numRings-1)

        radial_offset = rIdx * ...
            (params.thickness + params.spacing);

        scale = base_radius - radial_offset;

        if scale <= params.thickness

            break;
        end

        % ========================================================
        % EXACT GIELIS RING
        % ========================================================
        [xo,yo,xi,yi] = ...
            generateGielisRing( ...
            params.m, ...
            params.n1, ...
            params.n2, ...
            params.n3, ...
            scale, ...
            params.thickness, ...
            params.gap, ...
            params.res);

        geom{end+1} = struct( ...
            'outerX', xo, ...
            'outerY', yo, ...
            'innerX', xi, ...
            'innerY', yi);
    end

    % ============================================================
    % SPIRAL
    % ============================================================
elseif strcmp(params.type,'spiral')

    if params.offset <= params.thickness

        params.offset = ...
            params.thickness + 0.05;
    end

    for rIdx = 0:(params.numRings-1)

        spiral_a = rIdx * params.offset;

        % ========================================================
        % CENTERLINE
        % ========================================================
        [x,y] = generateSpiral( ...
            spiral_a, ...
            params.b, ...
            params.turns, ...
            params.res);

        % ========================================================
        % BUILD CONTOURS
        % ========================================================
        [xo,yo,xi,yi] = ...
            buildClosedContours( ...
            x, y, ...
            params.thickness, ...
            params.gap);

        geom{end+1} = struct( ...
            'outerX', xo, ...
            'outerY', yo, ...
            'innerX', xi, ...
            'innerY', yi);
    end

    % ============================================================
    % SQUARE SRR
    % ============================================================
elseif strcmp(params.type,'ssrr')

    if params.spacing <= params.thickness

        params.spacing = ...
            params.thickness + 0.05;
    end

    for rIdx = 0:(params.numRings-1)

        side = params.side - ...
            rIdx * ...
            (params.spacing + params.thickness);

        if side <= 2*params.thickness

            break;
        end

        % ========================================================
        % EXACT POLYGONAL GEOMETRY
        % ========================================================
        [xo,yo,xi,yi] = ...
            generateSquareSRR( ...
            side, ...
            params.thickness, ...
            params.gap);

        geom{end+1} = struct( ...
            'outerX', xo, ...
            'outerY', yo, ...
            'innerX', xi, ...
            'innerY', yi);
    end
end