function MetamaterialCAD()

    % ============================================================
    % MAIN WINDOW
    % ============================================================
    fig = uifigure( ...
        'Name','Metamaterial CAD', ...
        'Position',[100 100 1450 850]);

    % ============================================================
    % AXES
    % ============================================================
    ax = uiaxes(fig, ...
        'Position',[470 60 940 760]);

    axis(ax,'equal');
    grid(ax,'on');
    hold(ax,'on');

    title(ax,'Metamaterial Preview');

    % ============================================================
    % GEOMETRY TYPE
    % ============================================================
    uilabel(fig, ...
        'Text','Geometry', ...
        'FontWeight','bold', ...
        'Position',[20 800 100 22]);

    geometryDrop = uidropdown(fig, ...
        'Position',[120 800 220 22], ...
        'Items',{'Gielis','Spiral','Square SRR'}, ...
        'Value','Gielis');

    % ============================================================
    % MODE
    % ============================================================
    uilabel(fig, ...
        'Text','Mode', ...
        'FontWeight','bold', ...
        'Position',[20 760 100 22]);

    modeDrop = uidropdown(fig, ...
        'Position',[120 760 220 22], ...
        'Items',{'SRR','CSRR'}, ...
        'Value','SRR');

    % ============================================================
    % STRUCTURE TYPE
    % ============================================================
    uilabel(fig, ...
        'Text','Structure', ...
        'FontWeight','bold', ...
        'Position',[20 720 100 22]);

    structureDrop = uidropdown(fig, ...
        'Position',[120 720 220 22], ...
        'Items',{'Single','Array'}, ...
        'Value','Single');

    % ============================================================
    % SHARED PARAMETERS
    % ============================================================
    sharedPanel = uipanel(fig, ...
        'Title','Shared Parameters', ...
        'Position',[20 500 420 190]);

    ringsSlider = createSlider( ...
        sharedPanel, ...
        'Rings', ...
        2,[1 10], ...
        130);

    thicknessSlider = createSlider( ...
        sharedPanel, ...
        'Thickness', ...
        0.15,[0.01 2], ...
        90);

    gapSlider = createSlider( ...
        sharedPanel, ...
        'Gap (deg)', ...
        20,[1 180], ...
        50);

    spacingSlider = createSlider( ...
        sharedPanel, ...
        'Spacing', ...
        0.2,[0.01 5], ...
        10);

    % ============================================================
    % GIELIS PANEL
    % ============================================================
    gielisPanel = uipanel(fig, ...
        'Title','Gielis Parameters', ...
        'Position',[20 230 420 250]);

    mSlider = createSlider( ...
        gielisPanel, ...
        'm', ...
        6,[1 20], ...
        180);

    n1Slider = createSlider( ...
        gielisPanel, ...
        'n1', ...
        1,[0.1 20], ...
        140);

    n2Slider = createSlider( ...
        gielisPanel, ...
        'n2', ...
        1,[0.1 20], ...
        100);

    n3Slider = createSlider( ...
        gielisPanel, ...
        'n3', ...
        1,[0.1 20], ...
        60);

    aSlider = createSlider( ...
        gielisPanel, ...
        'Radius', ...
        5,[1 20], ...
        20);

    % ============================================================
    % SPIRAL PANEL
    % ============================================================
    spiralPanel = uipanel(fig, ...
        'Title','Spiral Parameters', ...
        'Position',[20 230 420 250], ...
        'Visible','off');

    growthSlider = createSlider( ...
        spiralPanel, ...
        'Growth', ...
        0.25,[0.01 2], ...
        180);

    turnsSlider = createSlider( ...
        spiralPanel, ...
        'Turns', ...
        4,[1 15], ...
        120);

    offsetSlider = createSlider( ...
        spiralPanel, ...
        'Offset', ...
        0.3,[0.05 5], ...
        60);

    % ============================================================
    % SSRR PANEL
    % ============================================================
    ssrrPanel = uipanel(fig, ...
        'Title','Square SRR Parameters', ...
        'Position',[20 230 420 250], ...
        'Visible','off');

    sideSlider = createSlider( ...
        ssrrPanel, ...
        'Side', ...
        5,[1 20], ...
        180);

    cornerSlider = createSlider( ...
        ssrrPanel, ...
        'Corner Radius', ...
        0,[0 2], ...
        120);

    % ============================================================
    % ARRAY PANEL
    % ============================================================
    arrayPanel = uipanel(fig, ...
        'Title','Array Parameters', ...
        'Position',[20 90 420 120], ...
        'Visible','off');

    NxSlider = createSlider( ...
        arrayPanel, ...
        'Nx', ...
        3,[1 20], ...
        70);

    NySlider = createSlider( ...
        arrayPanel, ...
        'Ny', ...
        3,[1 20], ...
        35);

    dxSlider = createSlider( ...
        arrayPanel, ...
        'dx', ...
        15,[1 100], ...
        0);

    dySlider = createSlider( ...
        arrayPanel, ...
        'dy', ...
        15,[1 100], ...
        -35);

    % ============================================================
    % SUBSTRATE PANEL
    % ============================================================
    substratePanel = uipanel(fig, ...
        'Title','Substrate', ...
        'Position',[20 10 420 60]);

    subSizeSlider = createSlider( ...
        substratePanel, ...
        'Size', ...
        50,[5 200], ...
        0);

    % ============================================================
    % EXPORT BUTTON
    % ============================================================
    uibutton(fig, ...
        'Text','Export to CST', ...
        'Position',[1240 10 160 35], ...
        'ButtonPushedFcn', ...
        @(src,event) exportCurrentDesign());

    % ============================================================
    % CALLBACKS
    % ============================================================
    geometryDrop.ValueChangedFcn = @(~,~) toggleGeometry();
    structureDrop.ValueChangedFcn = @(~,~) toggleArray();

    sliders = findall(fig,'Type','uislider');

    for k = 1:length(sliders)

        sliders(k).ValueChangedFcn = @(~,~) updatePlot();
    end

    modeDrop.ValueChangedFcn = @(~,~) updatePlot();

    updatePlot();

    % ============================================================
    % TOGGLE GEOMETRY
    % ============================================================
    function toggleGeometry()

        gielisPanel.Visible = 'off';
        spiralPanel.Visible = 'off';
        ssrrPanel.Visible = 'off';

        switch geometryDrop.Value

            case 'Gielis'
                gielisPanel.Visible = 'on';

            case 'Spiral'
                spiralPanel.Visible = 'on';

            case 'Square SRR'
                ssrrPanel.Visible = 'on';
        end

        updatePlot();
    end

    % ============================================================
    % TOGGLE ARRAY
    % ============================================================
    function toggleArray()

        if strcmp(structureDrop.Value,'Array')

            arrayPanel.Visible = 'on';

        else

            arrayPanel.Visible = 'off';
        end

        updatePlot();
    end

    % ============================================================
    % COLLECT PARAMETERS
    % ============================================================
    function params = collectParams()

        % ========================================================
        % TYPE
        % ========================================================
        switch geometryDrop.Value

            case 'Gielis'
                params.type = 'gielis';

            case 'Spiral'
                params.type = 'spiral';

            case 'Square SRR'
                params.type = 'ssrr';
        end

        % ========================================================
        % SHARED
        % ========================================================
        params.mode = modeDrop.Value;

        params.numRings = round(ringsSlider.Value);

        params.thickness = thicknessSlider.Value;

        params.gap = deg2rad(gapSlider.Value);

        params.spacing = spacingSlider.Value;

        params.res = 1500;

        % ========================================================
        % GIELIS
        % ========================================================
        params.m = mSlider.Value;
        params.n1 = n1Slider.Value;
        params.n2 = n2Slider.Value;
        params.n3 = n3Slider.Value;

        params.a = aSlider.Value;

        % ========================================================
        % SPIRAL
        % ========================================================
        params.b = growthSlider.Value;

        params.turns = turnsSlider.Value;

        params.offset = offsetSlider.Value;

        % ========================================================
        % SSRR
        % ========================================================
        params.side = sideSlider.Value;

        params.corner = cornerSlider.Value;

        % ========================================================
        % ARRAY
        % ========================================================
        params.Nx = round(NxSlider.Value);

        params.Ny = round(NySlider.Value);

        params.dx = dxSlider.Value;

        params.dy = dySlider.Value;

        % ========================================================
        % SUBSTRATE
        % ========================================================
        params.substrateSize = subSizeSlider.Value;

        params.substrateThickness = 1.6;

        params.substrateMaterial = 'FR4';
    end

    % ============================================================
    % UPDATE PLOT
    % ============================================================
    function updatePlot()

        cla(ax);

        params = collectParams();

        % ========================================================
        % BUILD GEOMETRY
        % ========================================================
        geom = buildMetamaterial(params);

        % ========================================================
        % ARRAY
        % ========================================================
        if strcmp(structureDrop.Value,'Array')

            geom = buildArray( ...
                geom, ...
                params.Nx, ...
                params.Ny, ...
                params.dx, ...
                params.dy, ...
                0,0, ...
                true);
        end

        hold(ax,'on');

        % ========================================================
        % SUBSTRATE
        % ========================================================
        L = params.substrateSize;

        rectangle(ax, ...
            'Position',[-L/2 -L/2 L L], ...
            'FaceColor',[0.85 0.85 0.85], ...
            'EdgeColor','k');

        % ========================================================
        % GROUND
        % ========================================================
        if strcmp(params.mode,'CSRR')

            rectangle(ax, ...
                'Position',[-L/2 -L/2 L L], ...
                'FaceColor',[0.45 0.45 0.45], ...
                'EdgeColor','none');
        end

        % ========================================================
        % DRAW GEOMETRIES
        % ========================================================
        for i = 1:length(geom)

            xo = geom{i}.outerX;
            yo = geom{i}.outerY;

            xi = geom{i}.innerX;
            yi = geom{i}.innerY;

            % ====================================================
            % BUILD CLOSED REGION
            % ====================================================
            X = [xo fliplr(xi)];
            Y = [yo fliplr(yi)];

            if strcmp(params.mode,'SRR')

                patch(ax, ...
                    X,Y, ...
                    [0.8 0 0], ...
                    'FaceAlpha',0.5, ...
                    'EdgeColor','r');

            else

                patch(ax, ...
                    X,Y, ...
                    'w', ...
                    'EdgeColor','none');
            end
        end

        axis(ax,'equal');

        xlabel(ax,'x (mm)');
        ylabel(ax,'y (mm)');

        grid(ax,'on');
    end

    % ============================================================
    % EXPORT
    % ============================================================
    function exportCurrentDesign()

        params = collectParams();

        geom = buildMetamaterial(params);

        if strcmp(structureDrop.Value,'Array')

            geom = buildArray( ...
                geom, ...
                params.Nx, ...
                params.Ny, ...
                params.dx, ...
                params.dy, ...
                0,0, ...
                true);
        end

        exportToCST_COM(geom,params);

        uialert(fig, ...
            'CST model generated successfully.', ...
            'Export');
    end
end

% ================================================================
% SLIDER FACTORY
% ================================================================
function slider = createSlider( ...
    parent, ...
    label, ...
    value, ...
    limits, ...
    ypos)

    uilabel(parent, ...
        'Text',label, ...
        'Position',[10 ypos+5 100 22]);

    slider = uislider(parent, ...
        'Position',[120 ypos+15 240 3], ...
        'Limits',limits, ...
        'Value',value);

    valueLabel = uilabel(parent, ...
        'Text',num2str(value,'%.2f'), ...
        'Position',[370 ypos+5 50 22]);

    slider.ValueChangedFcn = @(src,event) ...
        set(valueLabel,'Text', ...
        num2str(src.Value,'%.2f'));
end