function cmd = buildCSTSubtract(outerSheet,innerSheet,component)
%BUILDCSTSUBTRACT Boolean subtract innerSheet from outerSheet.
%   component (optional) default 'component1'

if nargin < 3 || isempty(component)
    component = 'component1';
end

cmd = sprintf([ ...
'Solid.Subtract ' ...
'"%s:%s", ' ...
'"%s:%s"\n'], ...
component, outerSheet, ...
component, innerSheet);
