function cmd = buildCSTMaterial(materialName)
% buildCSTMaterial
%
% Generates the CST VBA code required to create one material.
%
% Input:
%   materialName:
%       'Copper (annealed)'
%       'Copper (pure)'
%       'FR-4 (lossy)'
%       'Rogers 2929 (lossy)'
%
% Output:
%   cmd: VBA command string for CST AddToHistory.

    switch materialName

        % ========================================================
        % COPPER ANNEALED
        % ========================================================
        case 'Copper (annealed)'

            cmd = [ ...
                'With Material' newline ...
                '    .Reset' newline ...
                '    .Name "Copper (annealed)"' newline ...
                '    .Folder ""' newline ...
                '    .FrqType "static"' newline ...
                '    .Type "Normal"' newline ...
                '    .SetMaterialUnit "Hz", "mm"' newline ...
                '    .Epsilon "1"' newline ...
                '    .Mu "1.0"' newline ...
                '    .Kappa "5.8e+007"' newline ...
                '    .TanD "0.0"' newline ...
                '    .TanDFreq "0.0"' newline ...
                '    .TanDGiven "False"' newline ...
                '    .TanDModel "ConstTanD"' newline ...
                '    .KappaM "0"' newline ...
                '    .TanDM "0.0"' newline ...
                '    .TanDMFreq "0.0"' newline ...
                '    .TanDMGiven "False"' newline ...
                '    .TanDMModel "ConstTanD"' newline ...
                '    .DispModelEps "None"' newline ...
                '    .DispModelMu "None"' newline ...
                '    .DispersiveFittingSchemeEps "Nth Order"' newline ...
                '    .DispersiveFittingSchemeMu "Nth Order"' newline ...
                '    .UseGeneralDispersionEps "False"' newline ...
                '    .UseGeneralDispersionMu "False"' newline ...
                '    .FrqType "all"' newline ...
                '    .Type "Lossy metal"' newline ...
                '    .SetMaterialUnit "GHz", "mm"' newline ...
                '    .Mu "1.0"' newline ...
                '    .Kappa "5.8e+007"' newline ...
                '    .Rho "8930.0"' newline ...
                '    .ThermalType "Normal"' newline ...
                '    .ThermalConductivity "401.0"' newline ...
                '    .SpecificHeat "390", "J/K/kg"' newline ...
                '    .MetabolicRate "0"' newline ...
                '    .BloodFlow "0"' newline ...
                '    .VoxelConvection "0"' newline ...
                '    .MechanicsType "Isotropic"' newline ...
                '    .YoungsModulus "120"' newline ...
                '    .PoissonsRatio "0.33"' newline ...
                '    .ThermalExpansionRate "17"' newline ...
                '    .Colour "1", "1", "0"' newline ...
                '    .Wireframe "False"' newline ...
                '    .Reflection "False"' newline ...
                '    .Allowoutline "True"' newline ...
                '    .Transparentoutline "False"' newline ...
                '    .Transparency "0"' newline ...
                '    .Create' newline ...
                'End With' newline];


        % ========================================================
        % COPPER PURE
        % ========================================================
        case 'Copper (pure)'

            cmd = [ ...
                'With Material' newline ...
                '    .Reset' newline ...
                '    .Name "Copper (pure)"' newline ...
                '    .Folder ""' newline ...
                '    .FrqType "all"' newline ...
                '    .Type "Lossy metal"' newline ...
                '    .MaterialUnit "Frequency", "GHz"' newline ...
                '    .MaterialUnit "Geometry", "mm"' newline ...
                '    .MaterialUnit "Time", "s"' newline ...
                '    .MaterialUnit "Temperature", "Kelvin"' newline ...
                '    .Mu "1.0"' newline ...
                '    .Sigma "5.96e+007"' newline ...
                '    .Rho "8930.0"' newline ...
                '    .ThermalType "Normal"' newline ...
                '    .ThermalConductivity "401.0"' newline ...
                '    .SpecificHeat "390", "J/K/kg"' newline ...
                '    .MetabolicRate "0"' newline ...
                '    .BloodFlow "0"' newline ...
                '    .VoxelConvection "0"' newline ...
                '    .MechanicsType "Isotropic"' newline ...
                '    .YoungsModulus "120"' newline ...
                '    .PoissonsRatio "0.33"' newline ...
                '    .ThermalExpansionRate "17"' newline ...
                '    .ReferenceCoordSystem "Global"' newline ...
                '    .CoordSystemType "Cartesian"' newline ...
                '    .NLAnisotropy "False"' newline ...
                '    .NLAStackingFactor "1"' newline ...
                '    .NLADirectionX "1"' newline ...
                '    .NLADirectionY "0"' newline ...
                '    .NLADirectionZ "0"' newline ...
                '    .FrqType "static"' newline ...
                '    .Type "Normal"' newline ...
                '    .SetMaterialUnit "Hz", "mm"' newline ...
                '    .Epsilon "1"' newline ...
                '    .Mu "1.0"' newline ...
                '    .Kappa "5.96e+007"' newline ...
                '    .TanD "0.0"' newline ...
                '    .TanDFreq "0.0"' newline ...
                '    .TanDGiven "False"' newline ...
                '    .TanDModel "ConstTanD"' newline ...
                '    .KappaM "0"' newline ...
                '    .TanDM "0.0"' newline ...
                '    .TanDMFreq "0.0"' newline ...
                '    .TanDMGiven "False"' newline ...
                '    .TanDMModel "ConstTanD"' newline ...
                '    .DispModelEps "None"' newline ...
                '    .DispModelMu "None"' newline ...
                '    .DispersiveFittingSchemeEps "Nth Order"' newline ...
                '    .DispersiveFittingSchemeMu "Nth Order"' newline ...
                '    .UseGeneralDispersionEps "False"' newline ...
                '    .UseGeneralDispersionMu "False"' newline ...
                '    .Colour "1", "1", "0"' newline ...
                '    .Wireframe "False"' newline ...
                '    .Reflection "False"' newline ...
                '    .Allowoutline "True"' newline ...
                '    .Transparentoutline "False"' newline ...
                '    .Transparency "0"' newline ...
                '    .Create' newline ...
                'End With' newline];


        % ========================================================
        % FR-4 LOSSY
        % ========================================================
        case 'FR-4 (lossy)'

            cmd = [ ...
                'With Material' newline ...
                '    .Reset' newline ...
                '    .Name "FR-4 (lossy)"' newline ...
                '    .Folder ""' newline ...
                '    .FrqType "all"' newline ...
                '    .Type "Normal"' newline ...
                '    .SetMaterialUnit "GHz", "mm"' newline ...
                '    .Epsilon "4.3"' newline ...
                '    .Mu "1.0"' newline ...
                '    .Kappa "0.0"' newline ...
                '    .TanD "0.025"' newline ...
                '    .TanDFreq "10.0"' newline ...
                '    .TanDGiven "True"' newline ...
                '    .TanDModel "ConstTanD"' newline ...
                '    .KappaM "0.0"' newline ...
                '    .TanDM "0.0"' newline ...
                '    .TanDMFreq "0.0"' newline ...
                '    .TanDMGiven "False"' newline ...
                '    .TanDMModel "ConstKappa"' newline ...
                '    .DispModelEps "None"' newline ...
                '    .DispModelMu "None"' newline ...
                '    .DispersiveFittingSchemeEps "General 1st"' newline ...
                '    .DispersiveFittingSchemeMu "General 1st"' newline ...
                '    .UseGeneralDispersionEps "False"' newline ...
                '    .UseGeneralDispersionMu "False"' newline ...
                '    .Rho "0.0"' newline ...
                '    .ThermalType "Normal"' newline ...
                '    .ThermalConductivity "0.3"' newline ...
                '    .SetActiveMaterial "all"' newline ...
                '    .Colour "0.94", "0.82", "0.76"' newline ...
                '    .Wireframe "False"' newline ...
                '    .Transparency "0"' newline ...
                '    .Create' newline ...
                'End With' newline];


        % ========================================================
        % ROGERS 2929 LOSSY
        % ========================================================
        case 'Rogers 2929 (lossy)'

            cmd = [ ...
                'With Material' newline ...
                '    .Reset' newline ...
                '    .Name "Rogers 2929 (lossy)"' newline ...
                '    .Folder ""' newline ...
                '    .FrqType "all"' newline ...
                '    .Type "Normal"' newline ...
                '    .SetMaterialUnit "GHz", "mm"' newline ...
                '    .Epsilon "2.99"' newline ...
                '    .Mu "1.0"' newline ...
                '    .Kappa "0.0"' newline ...
                '    .TanD "0.0028"' newline ...
                '    .TanDFreq "10.0"' newline ...
                '    .TanDGiven "True"' newline ...
                '    .TanDModel "ConstTanD"' newline ...
                '    .KappaM "0.0"' newline ...
                '    .TanDM "0.0"' newline ...
                '    .TanDMFreq "0.0"' newline ...
                '    .TanDMGiven "False"' newline ...
                '    .TanDMModel "ConstKappa"' newline ...
                '    .DispModelEps "None"' newline ...
                '    .DispModelMu "None"' newline ...
                '    .DispersiveFittingSchemeEps "General 1st"' newline ...
                '    .DispersiveFittingSchemeMu "General 1st"' newline ...
                '    .UseGeneralDispersionEps "False"' newline ...
                '    .UseGeneralDispersionMu "False"' newline ...
                '    .Rho "0.0"' newline ...
                '    .ThermalType "Normal"' newline ...
                '    .ThermalConductivity "0.4"' newline ...
                '    .SetActiveMaterial "all"' newline ...
                '    .Colour "0.94", "0.82", "0.76"' newline ...
                '    .Wireframe "False"' newline ...
                '    .Transparency "0"' newline ...
                '    .Create' newline ...
                'End With' newline];


        otherwise

            error( ...
                'Unsupported CST material: %s', ...
                materialName);
    end
end