function cmd = buildCSTCurve(X,Y,Z,name,curveFolder)
%BUILDCSTCURVE Closed 3D polygon for CST.
%   curveFolder (optional) = CST curve folder name. Default 'Curve1'.
%   Using a unique folder per export avoids name collisions.

if nargin < 5 || isempty(curveFolder)
    curveFolder = 'Curve1';
end

cmd = '';

cmd = [cmd ...
    'With Polygon3D' newline ...
    '    .Reset' newline];

cmd = [cmd ...
    sprintf('    .Name "%s"\n',name)];

cmd = [cmd ...
    sprintf('    .Curve "%s"\n',curveFolder)];

for n = 1:length(X)

    cmd = [cmd ...
        sprintf( ...
        '    .Point "%f", "%f", "%f"\n', ...
        X(n), ...
        Y(n), ...
        Z)];
end

cmd = [cmd ...
    '    .Create' newline ...
    'End With' newline newline];
