function cmd = buildCSTSheet(curveName,sheetName,material)

cmd = '';

cmd = [cmd ...
    'With CoverCurve' newline ...
    '    .Reset' newline];

cmd = [cmd ...
    sprintf('    .Name "%s"\n',sheetName)];

cmd = [cmd ...
    '    .Component "component1"' newline];

cmd = [cmd ...
    sprintf('    .Material "%s"\n',material)];

cmd = [cmd ...
    sprintf('    .Curve "Curve1:%s"\n',curveName)];

cmd = [cmd ...
    '    .Create' newline ...
    'End With' newline newline];