function cmd = buildCSTBrick( ...
    name, component, material, ...
    xmin,xmax, ...
    ymin,ymax, ...
    zmin,zmax)

cmd = sprintf([ ...
'With Brick\n' ...
'.Reset\n' ...
'.Name "%s"\n' ...
'.Component "%s"\n' ...
'.Material "%s"\n' ...
'.Xrange "%f","%f"\n' ...
'.Yrange "%f","%f"\n' ...
'.Zrange "%f","%f"\n' ...
'.Create\n' ...
'End With\n\n'], ...
name, ...
component, ...
material, ...
xmin,xmax, ...
ymin,ymax, ...
zmin,zmax);