function cmd = buildCSTMaterial(params)

    switch params.substrateMaterial

        case 'FR4'

            eps = 4.3;
            tand = 0.02;

        case 'Rogers5880'

            eps = 2.2;
            tand = 0.0009;

        otherwise

            eps = 1;
            tand = 0;
    end

    cmd = sprintf([ ...
        'With Material\n' ...
        '.Reset\n' ...
        '.Name "SubstrateMat"\n' ...
        '.Folder ""\n' ...
        '.Type "Normal"\n' ...
        '.Epsilon "%f"\n' ...
        '.Mue "1"\n' ...
        '.TanD "%f"\n' ...
        '.Create\n' ...
        'End With\n\n'], ...
        eps, tand);
end