function exportToCST_COM(geom,params)

% ============================================================
% OPEN CST
% ============================================================
cst = actxserver('CSTStudio.Application');

mws = cst.NewMWS;

% ============================================================
% STORE PARAMETERS
% ============================================================
paramCode = sprintf([ ...
    'StoreParameter "subSize", %f\n' ...
    'StoreParameter "subH", %f\n'], ...
    params.substrateSize, ...
    params.substrateThickness);

invoke(mws, ...
    'AddToHistory', ...
    'Store Parameters', ...
    paramCode);
% ============================================================
% SOLVER TYPE
% ============================================================
invoke(mws, ...
    'AddToHistory', ...
    'Change Solver Type', ...
    'ChangeSolverType "HF Frequency Domain"');


% ============================================================
% FREQUENCY RANGE
% ============================================================
invoke(mws, ...
    'AddToHistory', ...
    'Frequency Range', ...
    'Solver.FrequencyRange "2", "12"');
% ============================================================
% UNITS
% ============================================================
unitsCode = [ ...
    'With Units' newline ...
    '    .Geometry "mm"' newline ...
    '    .Frequency "GHz"' newline ...
    '    .Time "ns"' newline ...
    'End With'];

invoke(mws, ...
    'AddToHistory', ...
    'Define Units', ...
    unitsCode);

% ============================================================
% CREATE SELECTED CONDUCTOR MATERIAL
% ============================================================
conductorCode = ...
    buildCSTMaterial(params.conductorMaterial);

invoke(mws, ...
    'AddToHistory', ...
    ['Create ', params.conductorMaterial], ...
    conductorCode);


% ============================================================
% CREATE SELECTED DIELECTRIC MATERIAL
% ============================================================
dielectricCode = ...
    buildCSTMaterial(params.dielectricMaterial);

invoke(mws, ...
    'AddToHistory', ...
    ['Create ', params.dielectricMaterial], ...
    dielectricCode);

% ============================================================
% SUBSTRATE
% ============================================================
L = params.substrateSize;
h = params.substrateThickness;

substrateCode = buildCSTBrick( ...
    'Substrate', ...
    'component1', ...
    params.dielectricMaterial, ...
    -L/2, L/2, ...
    -L/2, L/2, ...
    0, h);

invoke(mws, ...
    'AddToHistory', ...
    'Create Substrate', ...
    substrateCode);

% ============================================================
% GROUND
% ============================================================
if strcmpi(params.portType,'GND')

    groundThickness = 0.035;   % Copper thickness in mm

    groundCode = buildCSTBrick( ...
        'Ground', ...
        'component1', ...
        params.conductorMaterial, ...
        -L/2, L/2, ...
        -L/2, L/2, ...
        -groundThickness, 0);

    invoke(mws, ...
        'AddToHistory', ...
        'Create Ground Plane', ...
        groundCode);

end

% ============================================================
% METAMATERIALS
% ============================================================
for k = 1:length(geom)

    g = geom{k};

    outerCurve = sprintf('Outer%d',k);
    innerCurve = sprintf('Inner%d',k);

    outerSheet = sprintf('OuterSheet%d',k);
    innerSheet = sprintf('InnerSheet%d',k);

    % ========================================================
    % OUTER CURVE
    % ========================================================
    outerCurveCmd = buildCSTCurve( ...
        g.outerX, ...
        g.outerY, ...
        h, ...
        outerCurve);

    invoke(mws, ...
        'AddToHistory', ...
        ['Outer Curve ',num2str(k)], ...
        outerCurveCmd);

    % ========================================================
    % INNER CURVE
    % ========================================================
    innerCurveCmd = buildCSTCurve( ...
        g.innerX, ...
        g.innerY, ...
        h, ...
        innerCurve);

    invoke(mws, ...
        'AddToHistory', ...
        ['Inner Curve ',num2str(k)], ...
        innerCurveCmd);

    % ========================================================
    % OUTER SHEET
    % ========================================================
    outerSheetCmd = buildCSTSheet( ...
        outerCurve, ...
        outerSheet, ...
        params.conductorMaterial);

    invoke(mws, ...
        'AddToHistory', ...
        ['Outer Sheet ',num2str(k)], ...
        outerSheetCmd);

    % ========================================================
    % INNER SHEET
    % ========================================================
    innerSheetCmd = buildCSTSheet( ...
        innerCurve, ...
        innerSheet, ...
        'Vacuum');

    invoke(mws, ...
        'AddToHistory', ...
        ['Inner Sheet ',num2str(k)], ...
        innerSheetCmd);

    % ========================================================
    % BOOLEAN SUBTRACT
    % ========================================================
    subtractCmd = buildCSTSubtract( ...
        outerSheet, ...
        innerSheet);

    invoke(mws, ...
        'AddToHistory', ...
        ['Subtract ',num2str(k)], ...
        subtractCmd);
end
% ============================================================
% TRANSLATE ZMIN SELECTION TO CST
% ============================================================
switch params.zminBoundary

    case 'Et=0'

        cstZminBoundary = 'electric';

    case 'Open'

        cstZminBoundary = 'open';

    case 'Open add space'

        cstZminBoundary = 'expanded open';

    otherwise

        error( ...
            'Unsupported Zmin boundary condition: %s', ...
            params.zminBoundary);
end


% ============================================================
% TRANSLATE ZMAX SELECTION TO CST
% ============================================================
switch params.zmaxBoundary

    case 'Et=0'

        cstZmaxBoundary = 'electric';

    case 'Open'

        cstZmaxBoundary = 'open';

    case 'Open add space'

        cstZmaxBoundary = 'expanded open';

    otherwise

        error( ...
            'Unsupported Zmax boundary condition: %s', ...
            params.zmaxBoundary);
end

% ============================================================
% BOUNDARIES
% ============================================================
boundaryCode = [ ...
    'With Boundary' newline ...
    '    .Xmin "unit cell"' newline ...
    '    .Xmax "unit cell"' newline ...
    '    .Ymin "unit cell"' newline ...
    '    .Ymax "unit cell"' newline ...
    sprintf('    .Zmin "%s"\n', cstZminBoundary) ...
    sprintf('    .Zmax "%s"\n', cstZmaxBoundary) ...
    '    .Xsymmetry "none"' newline ...
    '    .Ysymmetry "none"' newline ...
    '    .Zsymmetry "none"' newline ...
    '    .ApplyInAllDirections "False"' newline ...
    '    .XPeriodicShift "0.0"' newline ...
    '    .YPeriodicShift "0.0"' newline ...
    '    .ZPeriodicShift "0.0"' newline ...
    '    .PeriodicUseConstantAngles "False"' newline ...
    '    .SetPeriodicBoundaryAngles "0.0", "0.0"' newline ...
    '    .SetPeriodicBoundaryAnglesDirection "outward"' newline ...
    '    .ScanAngleRefFreq "0.0"' newline ...
    '    .UnitCellFitToBoundingBox "True"' newline ...
    '    .UnitCellDs1 "0.0"' newline ...
    '    .UnitCellDs2 "0.0"' newline ...
    '    .UnitCellAngle "90.0"' newline ...
    'End With'];

invoke(mws, ...
    'AddToHistory', ...
    'Boundaries', ...
    boundaryCode);
%=============
floquetCode = [ ...
    'With FloquetPort' newline ...
    '     .Reset' newline ...
    '     .SetDialogTheta "0"' newline ...
    '     .SetDialogPhi "0"' newline ...
    '     .SetPolarizationIndependentOfScanAnglePhi "0.0", "False"' newline ...
    '     .SetSortCode "+beta/pw"' newline ...
    '     .SetCustomizedListFlag "False"' newline ...
    '     .Port "Zmax"' newline ...
    '     .SetNumberOfModesConsidered "2"' newline ...
    '     .SetDistanceToReferencePlane "0.0"' newline ...
    '     .SetUseCircularPolarization "False"' newline ...
    'End With'];

invoke(mws, ...
    'AddToHistory', ...
    'Define Floquet Port', ...
    floquetCode);



% ============================================================
% BACKGROUND SPACE
% ============================================================
% ============================================================
% BACKGROUND SPACE
% ============================================================
backgroundCode = [ ...
    'With Background' newline ...
    '    .ResetBackground' newline ...
    '    .XminSpace "0.0"' newline ...
    '    .XmaxSpace "0.0"' newline ...
    '    .YminSpace "0.0"' newline ...
    '    .YmaxSpace "0.0"' newline ...
    sprintf('    .ZminSpace "%.6f"\n', params.substrateThickness) ...
    sprintf('    .ZmaxSpace "%.6f"\n', params.substrateThickness) ...
    '    .ApplyInAllDirections "False"' newline ...
    'End With'];

invoke(mws, ...
    'AddToHistory', ...
    'Define Background Space', ...
    backgroundCode);


% ============================================================
% BACKGROUND MATERIAL: VACUUM / AIR
% ============================================================
backgroundMaterialCode = [ ...
    'With Material' newline ...
    '    .Reset' newline ...
    '    .Type "Normal"' newline ...
    '    .Epsilon "1.0"' newline ...
    '    .Mu "1.0"' newline ...
    '    .Sigma "0.0"' newline ...
    '    .TanD "0.0"' newline ...
    '    .TanDM "0.0"' newline ...
    '    .ChangeBackgroundMaterial' newline ...
    'End With'];

invoke(mws, ...
    'AddToHistory', ...
    'Define Background Material', ...
    backgroundMaterialCode);
% ============================================================
% ZOOM
% ============================================================
invoke(mws, ...
    'AddToHistory', ...
    'Zoom', ...
    'Plot.ZoomToStructure');

disp('CST model generated successfully.');
end