function exportToCST_COM(geom,params)

% ============================================================
% OPEN CST
% ============================================================
cst = actxserver('CSTStudio.Application');

mws = cst.NewMWS;

% ============================================================
% STORE PARAMETERS
% ============================================================
paramCode = sprintf([ ...
    'StoreParameter "subSize", %f\n' ...
    'StoreParameter "subH", %f\n'], ...
    params.substrateSize, ...
    params.substrateThickness);

invoke(mws, ...
    'AddToHistory', ...
    'Store Parameters', ...
    paramCode);

% ============================================================
% UNITS
% ============================================================
unitsCode = [ ...
    'With Units' newline ...
    '    .Geometry "mm"' newline ...
    '    .Frequency "GHz"' newline ...
    '    .Time "ns"' newline ...
    'End With'];

invoke(mws, ...
    'AddToHistory', ...
    'Define Units', ...
    unitsCode);

% ============================================================
% MATERIAL
% ============================================================
materialCode = buildCSTMaterial(params);

invoke(mws, ...
    'AddToHistory', ...
    'Create Material', ...
    materialCode);

% ============================================================
% SUBSTRATE
% ============================================================
L = params.substrateSize;
h = params.substrateThickness;

substrateCode = buildCSTBrick( ...
    'Substrate', ...
    'component1', ...
    'SubstrateMat', ...
    -L/2, L/2, ...
    -L/2, L/2, ...
    0, h);

invoke(mws, ...
    'AddToHistory', ...
    'Create Substrate', ...
    substrateCode);

% ============================================================
% GROUND
% ============================================================
if strcmp(params.mode,'CSRR')

    groundCode = buildCSTBrick( ...
        'Ground', ...
        'component1', ...
        'PEC', ...
        -L/2, L/2, ...
        -L/2, L/2, ...
        h, h+0.035);

    invoke(mws, ...
        'AddToHistory', ...
        'Create Ground', ...
        groundCode);
end

% ============================================================
% METAMATERIALS
% ============================================================
for k = 1:length(geom)

    g = geom{k};

    outerCurve = sprintf('Outer%d',k);
    innerCurve = sprintf('Inner%d',k);

    outerSheet = sprintf('OuterSheet%d',k);
    innerSheet = sprintf('InnerSheet%d',k);

    % ========================================================
    % OUTER CURVE
    % ========================================================
    outerCurveCmd = buildCSTCurve( ...
        g.outerX, ...
        g.outerY, ...
        h, ...
        outerCurve);

    invoke(mws, ...
        'AddToHistory', ...
        ['Outer Curve ',num2str(k)], ...
        outerCurveCmd);

    % ========================================================
    % INNER CURVE
    % ========================================================
    innerCurveCmd = buildCSTCurve( ...
        g.innerX, ...
        g.innerY, ...
        h, ...
        innerCurve);

    invoke(mws, ...
        'AddToHistory', ...
        ['Inner Curve ',num2str(k)], ...
        innerCurveCmd);

    % ========================================================
    % OUTER SHEET
    % ========================================================
    outerSheetCmd = buildCSTSheet( ...
        outerCurve, ...
        outerSheet, ...
        'PEC');

    invoke(mws, ...
        'AddToHistory', ...
        ['Outer Sheet ',num2str(k)], ...
        outerSheetCmd);

    % ========================================================
    % INNER SHEET
    % ========================================================
    innerSheetCmd = buildCSTSheet( ...
        innerCurve, ...
        innerSheet, ...
        'Vacuum');

    invoke(mws, ...
        'AddToHistory', ...
        ['Inner Sheet ',num2str(k)], ...
        innerSheetCmd);

    % ========================================================
    % BOOLEAN SUBTRACT
    % ========================================================
    subtractCmd = buildCSTSubtract( ...
        outerSheet, ...
        innerSheet);

    invoke(mws, ...
        'AddToHistory', ...
        ['Subtract ',num2str(k)], ...
        subtractCmd);
end

% ============================================================
% BOUNDARIES
% ============================================================
boundaryCode = [ ...
    'With Boundary' newline ...
    '    .Xmin "open"' newline ...
    '    .Xmax "open"' newline ...
    '    .Ymin "open"' newline ...
    '    .Ymax "open"' newline ...
    '    .Zmin "open"' newline ...
    '    .Zmax "open"' newline ...
    'End With'];

invoke(mws, ...
    'AddToHistory', ...
    'Boundaries', ...
    boundaryCode);

% ============================================================
% ZOOM
% ============================================================
invoke(mws, ...
    'AddToHistory', ...
    'Zoom', ...
    'Plot.ZoomToStructure');

disp('CST model generated successfully.');
end