function exportToCST_COM(geom,params)

% ============================================================
% OPEN CST
% ============================================================
cst = actxserver('CSTStudio.Application');

mws = cst.NewMWS;

% ============================================================
% STORE PARAMETERS
% ============================================================
paramCode = sprintf([ ...
    'StoreParameter "subSize", %f\n' ...
    'StoreParameter "subH", %f\n'], ...
    params.substrateSize, ...
    params.substrateThickness);

invoke(mws, ...
    'AddToHistory', ...
    'Store Parameters', ...
    paramCode);
% ============================================================
% SOLVER TYPE
% ============================================================
invoke(mws, ...
    'AddToHistory', ...
    'Change Solver Type', ...
    'ChangeSolverType "HF Frequency Domain"');


% ============================================================
% FREQUENCY RANGE
% ============================================================
invoke(mws, ...
    'AddToHistory', ...
    'Frequency Range', ...
    'Solver.FrequencyRange "2", "12"');
% ============================================================
% UNITS
% ============================================================
unitsCode = [ ...
    'With Units' newline ...
    '    .Geometry "mm"' newline ...
    '    .Frequency "GHz"' newline ...
    '    .Time "ns"' newline ...
    'End With'];

invoke(mws, ...
    'AddToHistory', ...
    'Define Units', ...
    unitsCode);

% ============================================================
% CREATE SELECTED CONDUCTOR MATERIAL
% ============================================================
conductorCode = ...
    buildCSTMaterial(params.conductorMaterial);

invoke(mws, ...
    'AddToHistory', ...
    ['Create ', params.conductorMaterial], ...
    conductorCode);


% ============================================================
% CREATE SELECTED DIELECTRIC MATERIAL
% ============================================================
dielectricCode = ...
    buildCSTMaterial(params.dielectricMaterial);

invoke(mws, ...
    'AddToHistory', ...
    ['Create ', params.dielectricMaterial], ...
    dielectricCode);

% ============================================================
% SUBSTRATE
% ============================================================
L = params.substrateSize;
h = params.substrateThickness;

% In Array mode the board covers the whole Nx x Ny matrix
Lx = L;
Ly = L;

if isfield(params,'structure') && strcmp(params.structure,'Array')
    Lx = (params.Nx-1)*params.dx + L;
    Ly = (params.Ny-1)*params.dy + L;
end

substrateCode = buildCSTBrick( ...
    'Substrate', ...
    'component1', ...
    params.dielectricMaterial, ...
    -Lx/2, Lx/2, ...
    -Ly/2, Ly/2, ...
    0, h);

invoke(mws, ...
    'AddToHistory', ...
    'Create Substrate', ...
    substrateCode);

% ============================================================
% GROUND
% ============================================================
if strcmpi(params.portType,'GND')

    groundThickness = 0.035;   % Copper thickness in mm
    if isfield(params,'metalThickness') && params.metalThickness > 0
        groundThickness = params.metalThickness;
    end

    groundCode = buildCSTBrick( ...
        'Ground', ...
        'component1', ...
        params.conductorMaterial, ...
        -Lx/2, Lx/2, ...
        -Ly/2, Ly/2, ...
        -groundThickness, 0);

    invoke(mws, ...
        'AddToHistory', ...
        'Create Ground Plane', ...
        groundCode);

end

% ============================================================
% METAMATERIALS
%
% SRR  : each ring is copper (outer minus inner contour).
% CSRR : a copper plate covers the whole board top face and each
%        ring shape is etched out of it (slot = complement of SRR).
%
% Metal thickness (params.metalThickness, mm):
%   > 0 : real solids from z = h to z = h + t   (Extrude / Brick)
%   = 0 : zero-thickness sheets (legacy behaviour)
% ============================================================
isCSRR = isfield(params,'mode') && strcmpi(params.mode,'CSRR');

t = 0;
if isfield(params,'metalThickness')
    t = params.metalThickness;
end
isSolid = t > 0;

if isCSRR

    if isSolid
        % ---------------- Copper plate with thickness ---------------
        plateCmd = buildCSTBrick( ...
            'CSRR_Plate', ...
            'component1', ...
            params.conductorMaterial, ...
            -Lx/2, Lx/2, ...
            -Ly/2, Ly/2, ...
            h, h + t);

        invoke(mws,'AddToHistory','CSRR Plate',plateCmd);
    else
        % ---------------- Flat copper plate (sheet) -----------------
        plateCurveCmd = buildCSTCurve( ...
            [-Lx/2  Lx/2  Lx/2 -Lx/2 -Lx/2], ...
            [-Ly/2 -Ly/2  Ly/2  Ly/2 -Ly/2], ...
            h, ...
            'CSRR_PlateCurve');

        invoke(mws,'AddToHistory','CSRR Plate Curve',plateCurveCmd);

        plateSheetCmd = buildCSTSheet( ...
            'CSRR_PlateCurve', ...
            'CSRR_Plate', ...
            params.conductorMaterial);

        invoke(mws,'AddToHistory','CSRR Plate',plateSheetCmd);
    end
end

for k = 1:length(geom)

    g = geom{k};

    if numel(g.outerX) < 3
        continue;
    end

    outerCurve = sprintf('Outer%d',k);
    innerCurve = sprintf('Inner%d',k);

    outerSheet = sprintf('OuterSheet%d',k);
    innerSheet = sprintf('InnerSheet%d',k);

    hasInner = numel(g.innerX) >= 3 && numel(g.innerY) >= 3;

    % In CSRR the ring shape is only a cutting tool
    if isCSRR
        ringMaterial = 'Vacuum';
    else
        ringMaterial = params.conductorMaterial;
    end

    if isSolid

        % ====================================================
        % SOLID RING WITH REAL THICKNESS
        % ====================================================
        outerCmd = buildCSTExtrude( ...
            outerSheet, 'component1', ringMaterial, ...
            g.outerX, g.outerY, h, t);

        invoke(mws,'AddToHistory', ...
            ['Outer Solid ',num2str(k)],outerCmd);

        if hasInner
            innerCmd = buildCSTExtrude( ...
                innerSheet, 'component1', 'Vacuum', ...
                g.innerX, g.innerY, h, t);

            invoke(mws,'AddToHistory', ...
                ['Inner Solid ',num2str(k)],innerCmd);
        end

    else

        % ====================================================
        % FLAT SHEETS (zero thickness)
        % ====================================================
        outerCurveCmd = buildCSTCurve( ...
            g.outerX, g.outerY, h, outerCurve);

        invoke(mws,'AddToHistory', ...
            ['Outer Curve ',num2str(k)],outerCurveCmd);

        outerSheetCmd = buildCSTSheet( ...
            outerCurve, outerSheet, ringMaterial);

        invoke(mws,'AddToHistory', ...
            ['Outer Sheet ',num2str(k)],outerSheetCmd);

        if hasInner
            innerCurveCmd = buildCSTCurve( ...
                g.innerX, g.innerY, h, innerCurve);

            invoke(mws,'AddToHistory', ...
                ['Inner Curve ',num2str(k)],innerCurveCmd);

            innerSheetCmd = buildCSTSheet( ...
                innerCurve, innerSheet, 'Vacuum');

            invoke(mws,'AddToHistory', ...
                ['Inner Sheet ',num2str(k)],innerSheetCmd);
        end
    end

    % ========================================================
    % RING = OUTER - INNER  (Gielis). SSRR has no inner contour.
    % ========================================================
    if hasInner
        subtractCmd = buildCSTSubtract(outerSheet,innerSheet);

        invoke(mws,'AddToHistory', ...
            ['Subtract ',num2str(k)],subtractCmd);
    end

    % ========================================================
    % CSRR: ETCH THE RING OUT OF THE PLATE
    % ========================================================
    if isCSRR
        etchCmd = buildCSTSubtract('CSRR_Plate',outerSheet);

        invoke(mws,'AddToHistory', ...
            ['CSRR Etch ',num2str(k)],etchCmd);
    end
end

% ============================================================
% TRANSLATE ZMIN SELECTION TO CST
% ============================================================
switch params.zminBoundary

    case 'Et=0'

        cstZminBoundary = 'electric';

    case 'Open'

        cstZminBoundary = 'open';

    case 'Open add space'

        cstZminBoundary = 'expanded open';

    otherwise

        error( ...
            'Unsupported Zmin boundary condition: %s', ...
            params.zminBoundary);
end


% ============================================================
% TRANSLATE ZMAX SELECTION TO CST
% ============================================================
switch params.zmaxBoundary

    case 'Et=0'

        cstZmaxBoundary = 'electric';

    case 'Open'

        cstZmaxBoundary = 'open';

    case 'Open add space'

        cstZmaxBoundary = 'expanded open';

    otherwise

        error( ...
            'Unsupported Zmax boundary condition: %s', ...
            params.zmaxBoundary);
end

% ============================================================
% BOUNDARIES
% ============================================================
boundaryCode = [ ...
    'With Boundary' newline ...
    '    .Xmin "unit cell"' newline ...
    '    .Xmax "unit cell"' newline ...
    '    .Ymin "unit cell"' newline ...
    '    .Ymax "unit cell"' newline ...
    sprintf('    .Zmin "%s"\n', cstZminBoundary) ...
    sprintf('    .Zmax "%s"\n', cstZmaxBoundary) ...
    '    .Xsymmetry "none"' newline ...
    '    .Ysymmetry "none"' newline ...
    '    .Zsymmetry "none"' newline ...
    '    .ApplyInAllDirections "False"' newline ...
    '    .XPeriodicShift "0.0"' newline ...
    '    .YPeriodicShift "0.0"' newline ...
    '    .ZPeriodicShift "0.0"' newline ...
    '    .PeriodicUseConstantAngles "False"' newline ...
    '    .SetPeriodicBoundaryAngles "0.0", "0.0"' newline ...
    '    .SetPeriodicBoundaryAnglesDirection "outward"' newline ...
    '    .ScanAngleRefFreq "0.0"' newline ...
    '    .UnitCellFitToBoundingBox "True"' newline ...
    '    .UnitCellDs1 "0.0"' newline ...
    '    .UnitCellDs2 "0.0"' newline ...
    '    .UnitCellAngle "90.0"' newline ...
    'End With'];

invoke(mws, ...
    'AddToHistory', ...
    'Boundaries', ...
    boundaryCode);
%=============
floquetCode = [ ...
    'With FloquetPort' newline ...
    '     .Reset' newline ...
    '     .SetDialogTheta "0"' newline ...
    '     .SetDialogPhi "0"' newline ...
    '     .SetPolarizationIndependentOfScanAnglePhi "0.0", "False"' newline ...
    '     .SetSortCode "+beta/pw"' newline ...
    '     .SetCustomizedListFlag "False"' newline ...
    '     .Port "Zmax"' newline ...
    '     .SetNumberOfModesConsidered "2"' newline ...
    '     .SetDistanceToReferencePlane "0.0"' newline ...
    '     .SetUseCircularPolarization "False"' newline ...
    'End With'];

invoke(mws, ...
    'AddToHistory', ...
    'Define Floquet Port', ...
    floquetCode);



% ============================================================
% BACKGROUND SPACE
% ============================================================
% ============================================================
% BACKGROUND SPACE
% ============================================================
backgroundCode = [ ...
    'With Background' newline ...
    '    .ResetBackground' newline ...
    '    .XminSpace "0.0"' newline ...
    '    .XmaxSpace "0.0"' newline ...
    '    .YminSpace "0.0"' newline ...
    '    .YmaxSpace "0.0"' newline ...
    sprintf('    .ZminSpace "%.6f"\n', params.substrateThickness) ...
    sprintf('    .ZmaxSpace "%.6f"\n', params.substrateThickness) ...
    '    .ApplyInAllDirections "False"' newline ...
    'End With'];

invoke(mws, ...
    'AddToHistory', ...
    'Define Background Space', ...
    backgroundCode);


% ============================================================
% BACKGROUND MATERIAL: VACUUM / AIR
% ============================================================
backgroundMaterialCode = [ ...
    'With Material' newline ...
    '    .Reset' newline ...
    '    .Type "Normal"' newline ...
    '    .Epsilon "1.0"' newline ...
    '    .Mu "1.0"' newline ...
    '    .Sigma "0.0"' newline ...
    '    .TanD "0.0"' newline ...
    '    .TanDM "0.0"' newline ...
    '    .ChangeBackgroundMaterial' newline ...
    'End With'];

invoke(mws, ...
    'AddToHistory', ...
    'Define Background Material', ...
    backgroundMaterialCode);
% ============================================================
% ZOOM
% ============================================================
invoke(mws, ...
    'AddToHistory', ...
    'Zoom', ...
    'Plot.ZoomToStructure');

disp('CST model generated successfully.');
end