function MetamaterialCAD()
    addpath('../geometry');
    addpath('../cst');
    
    % ============================================================
    % MAIN WINDOW
    % ============================================================
    fig = uifigure(...
        'Name','Metamaterial CAD',...
        'Position',[100 100 1450 850]);
    % ============================================================
    % AXES
    % ============================================================
    ax = uiaxes(fig,...
        'Position',[470 60 940 760]);
    axis(ax,'equal');
    grid(ax,'on');
    hold(ax,'on');
    title(ax,'Metamaterial Preview');
    % ============================================================
    % GEOMETRY TYPE
    % ============================================================
    uilabel(fig,...
        'Text','Geometry',...
        'FontWeight','bold',...
        'Position',[20 800 100 22]);
    geometryDrop = uidropdown(fig,...
        'Position',[120 800 220 22],...
        'Items',{'Gielis','Square SRR'},...
        'Value','Gielis');
    % ============================================================
    % MODE
    % ============================================================
    uilabel(fig,...
        'Text','Mode',...
        'FontWeight','bold',...
        'Position',[20 760 100 22]);
    modeDrop = uidropdown(fig,...
        'Position',[120 760 220 22],...
        'Items',{'SRR','CSRR'},...
        'Value','SRR');
    % ============================================================
    % STRUCTURE TYPE
    % ============================================================
    uilabel(fig,...
        'Text','Structure',...
        'FontWeight','bold',...
        'Position',[20 720 100 22]);
    structureDrop = uidropdown(fig,...
        'Position',[120 720 220 22],...
        'Items',{'Single','Array'},...
        'Value','Single');
    % ============================================================
    % SHARED PARAMETERS
    % ============================================================
    sharedPanel = uipanel(fig,...
        'Title','Shared Parameters',...
        'Position',[20 500 420 190]);
    ringsSlider = createSlider(...
        sharedPanel,...
        'Rings',...
        2,[1 10],...
        130,...
        true); % Enforced strict integer
    thicknessSlider = createSlider(...
        sharedPanel,...
        'Thickness',...
        0.15,[0.01 2],...
        90);
    gapSlider = createSlider(...
        sharedPanel,...
        'Gap (deg)',...
        20,[1 180],...
        50); % Restored realistic angular limits
    spacingSlider = createSlider(...
        sharedPanel,...
        'Spacing',...
        0.2,[0.01 5],...
        10);
    % ============================================================
    % GIELIS PANEL
    % ============================================================
    gielisPanel = uipanel(fig,...
        'Title','Gielis Parameters',...
        'Position',[20 230 420 250]);
    mSlider = createSlider(...
        gielisPanel,...
        'm',...
        6,[1 20],...
        180,...
        true); % strict integer
    n1Slider = createSlider(...
        gielisPanel,...
        'n1',...
        1,[0.1 20],...
        140);
    n2Slider = createSlider(...
        gielisPanel,...
        'n2',...
        1,[0.1 20],...
        100);
    n3Slider = createSlider(...
        gielisPanel,...
        'n3',...
        1,[0.1 20],...
        60);
    aSlider = createSlider(...
        gielisPanel,...
        'Radius',...
        5,[1 20],...
        20);
    % ============================================================
    % SSRR PANEL
    % ============================================================
    ssrrPanel = uipanel(fig,...
        'Title','Square SRR Parameters',...
        'Position',[20 230 420 250],...
        'Visible','off');
    sideSlider = createSlider(...
        ssrrPanel,...
        'Side',...
        5,[1 20],...
        180);
    cornerSlider = createSlider(...
        ssrrPanel,...
        'Corner Radius',...
        0,[0 2],...
        120);
    % ============================================================
    % ARRAY PANEL
    % ============================================================
    arrayPanel = uipanel(fig,...
        'Title','Array Parameters',...
        'Position',[20 90 420 120],...
        'Visible','off');
    NxSlider = createSlider(...
        arrayPanel,...
        'Nx',...
        3,[1 20],...
        70,...
        true); % Enforced strict integer array elements
    NySlider = createSlider(...
        arrayPanel,...
        'Ny',...
        3,[1 20],...
        35,...
        true); % Enforced strict integer array elements
    dxSlider = createSlider(...
        arrayPanel,...
        'dx',...
        15,[1 100],...
        0);
    dySlider = createSlider(...
        arrayPanel,...
        'dy',...
        15,[1 100],...
        -35);
    % ============================================================
    % SUBSTRATE PANEL
    % ============================================================
    substratePanel = uipanel(fig,...
        'Title','Substrate',...
        'Position',[20 10 420 60]);
    subSizeSlider = createSlider(...
        substratePanel,...
        'Size',...
        50,[5 200],...
        0);
    % ============================================================
    % EXPORT BUTTON
    % ============================================================
    uibutton(fig,...
        'Text','Export to CST',...
        'Position',[1240 10 160 35],...
        'ButtonPushedFcn',...
        @(src,event) exportCurrentDesign());
    % ============================================================
    % CALLBACKS
    % ============================================================
    geometryDrop.ValueChangedFcn = @(~,~) toggleGeometry();
    structureDrop.ValueChangedFcn = @(~,~) toggleArray();
    modeDrop.ValueChangedFcn = @(~,~) updatePlot();
    
    % Execute initial render
    updatePlot();
    
    % ============================================================
    % TOGGLE GEOMETRY
    % ============================================================
    function toggleGeometry()
        gielisPanel.Visible = 'off';
        ssrrPanel.Visible = 'off';
        switch geometryDrop.Value
            case 'Gielis'
                gielisPanel.Visible = 'on';
            case 'Square SRR'
                ssrrPanel.Visible = 'on';
        end
        updatePlot();
    end
    % ============================================================
    % TOGGLE ARRAY
    % ============================================================
    function toggleArray()
        if strcmp(structureDrop.Value,'Array')
            arrayPanel.Visible = 'on';
        else
            arrayPanel.Visible = 'off';
        end
        updatePlot();
    end
    % ============================================================
    % COLLECT PARAMETERS
    % ============================================================
    function params = collectParams()
        switch geometryDrop.Value
            case 'Gielis'
                params.type = 'gielis';
            case 'Square SRR'
                params.type = 'ssrr';
        end
        params.mode = modeDrop.Value;
        params.numRings = round(ringsSlider.Value);
        params.thickness = thicknessSlider.Value;
        params.gap = deg2rad(gapSlider.Value);
        params.spacing = spacingSlider.Value;
        params.res = 1500;
        
        params.m = mSlider.Value;
        params.n1 = n1Slider.Value;
        params.n2 = n2Slider.Value;
        params.n3 = n3Slider.Value;
        params.a = aSlider.Value;

        params.side = sideSlider.Value;
        params.corner = cornerSlider.Value;
        
        params.Nx = round(NxSlider.Value);
        params.Ny = round(NySlider.Value);
        params.dx = dxSlider.Value;
        params.dy = dySlider.Value;
        
        params.substrateSize = subSizeSlider.Value;
        params.substrateThickness = 1.6;
        params.substrateMaterial = 'FR4';
    end
    % ============================================================
    % UPDATE PLOT
    % ============================================================
    function updatePlot()
        cla(ax);
        params = collectParams();
        geom = buildMetamaterial(params);
        if strcmp(structureDrop.Value,'Array')
            geom = buildArray(...
                geom,...
                params.Nx,...
                params.Ny,...
                params.dx,...
                params.dy,...
                0,0,...
                true);
        end
        hold(ax,'on');
        
        L = params.substrateSize;
        rectangle(ax,...
            'Position',[-L/2 -L/2 L L],...
            'FaceColor',[0.85 0.85 0.85],...
            'EdgeColor','k');
            
        if strcmp(params.mode,'CSRR')
            rectangle(ax,...
                'Position',[-L/2 -L/2 L L],...
                'FaceColor',[0.45 0.45 0.45],...
                'EdgeColor','none');
        end
        
        for i = 1:length(geom)
            xo = geom{i}.outerX;
            yo = geom{i}.outerY;
            xi = geom{i}.innerX;
            yi = geom{i}.innerY;
            X = [xo fliplr(xi)];
            Y = [yo fliplr(yi)];
            if strcmp(params.mode,'SRR')
                patch(ax,...
                    X,Y,...
                    [0.8 0 0],...
                    'FaceAlpha',0.5,...
                    'EdgeColor','r');
            else
                patch(ax,...
                    X,Y,...
                    'w',...
                    'EdgeColor','none');
            end
        end
        axis(ax,'equal');
        xlabel(ax,'x (mm)');
        ylabel(ax,'y (mm)');
        grid(ax,'on');
    end
    % ============================================================
    % EXPORT
    % ============================================================
    function exportCurrentDesign()
        params = collectParams();
        geom = buildMetamaterial(params);
        if strcmp(structureDrop.Value,'Array')
            geom = buildArray(...
                geom,...
                params.Nx,...
                params.Ny,...
                params.dx,...
                params.dy,...
                0,0,...
                true);
        end
        exportToCST_COM(geom,params);
        uialert(fig,...
            'CST model generated successfully.',...
            'Export');
    end

    % ============================================================
    % SLIDER FACTORY (NESTED FOR AUTOMATIC CALLBACK RESOLUTION)
    % ============================================================
    function slider = createSlider(...
        parent,...
        label,...
        value,...
        limits,...
        ypos,...
        isInteger)

        if nargin < 6
            isInteger = false; 
        end
        uilabel(parent,...
            'Text',label,...
            'Position',[10 ypos+5 100 22]);

        slider = uislider(parent,...
            'Position',[120 ypos+15 240 3],...
            'Limits',limits,...
            'Value',value);

        if isInteger
            slider.Value = round(value);
            valueLabel = uilabel(parent,...
                'Text',num2str(round(value),'%d'),...
                'Position',[370 ypos+5 50 22]);
            slider.ValueChangedFcn = @(src,event) updateIntegerSlider(src, valueLabel);
        else
            valueLabel = uilabel(parent,...
                'Text',num2str(value,'%.2f'),...
                'Position',[370 ypos+5 50 22]);
            slider.ValueChangedFcn = @(src,event) updateFloatSlider(src, valueLabel);
        end
    end

    % Inner Snapping Callbacks
    function updateIntegerSlider(src, label)
        src.Value = round(src.Value); % Snap handle to nearest integer
        set(label,'Text',num2str(src.Value,'%d'));
        updatePlot(); % Safely trigger redraw inside the scope
    end

    function updateFloatSlider(src, label)
        set(label,'Text',num2str(src.Value,'%.2f'));
        updatePlot(); % Safely trigger redraw inside the scope
    end

end % <-- FINAL METAMATERIALCAD() END TAG - HELPER FUNCTIONS ARE NOW INTEGRATED