function geom = buildMetamaterial(params)

geom = {};

% ============================================================
% GIELIS
% ============================================================
if strcmp(params.type,'gielis')

    if params.spacing <= params.thickness

        params.spacing = ...
            params.thickness + 0.05;
    end

    base_radius = params.a;

    for rIdx = 0:(params.numRings-1)

        radial_offset = rIdx * ...
            (params.thickness + params.spacing);

        scale = base_radius - radial_offset;

        if scale <= params.thickness
            break;
        end

        % ========================================================
        % EXACT GIELIS RING
        % ========================================================
        [xo,yo,xi,yi] = ...
            generateGielisRing( ...
            params.m, ...
            params.n1, ...
            params.n2, ...
            params.n3, ...
            scale, ...
            params.thickness, ...
            params.res);

        geom{end+1} = struct( ...
            'outerX', xo, ...
            'outerY', yo, ...
            'innerX', xi, ...
            'innerY', yi);
    end


% ============================================================
% SPIRAL
% ============================================================
elseif strcmp(params.type,'spiral')

    if params.offset <= params.thickness

        params.offset = ...
            params.thickness + 0.05;
    end

    for rIdx = 0:(params.numRings-1)

        spiral_a = rIdx * params.offset;

        % ========================================================
        % CENTERLINE
        % ========================================================
        [x,y] = generateSpiral( ...
            spiral_a, ...
            params.b, ...
            params.turns, ...
            params.res);

        % ========================================================
        % BUILD CONTOURS
        % ========================================================
        [xo,yo,xi,yi] = ...
            buildClosedContours( ...
            x, ...
            y, ...
            params.thickness, ...
            params.gap);

        geom{end+1} = struct( ...
            'outerX', xo, ...
            'outerY', yo, ...
            'innerX', xi, ...
            'innerY', yi);
    end


% ============================================================
% SQUARE / RECTANGULAR SRR
% ============================================================
elseif strcmp(params.type,'ssrr')

    requiredFields = { ...
        'W', ...
        'L', ...
        'numRings', ...
        'spacing', ...
        'thickness', ...
        'gapSSRR', ...
        'gapPositions'};

    for k = 1:length(requiredFields)

        if ~isfield(params,requiredFields{k})

            error( ...
                'Missing SSRR parameter: params.%s', ...
                requiredFields{k});
        end
    end


    geom = generateSquareSRR( ...
        params.W, ...
        params.L, ...
        params.numRings, ...
        params.spacing, ...
        params.thickness, ...
        params.gapSSRR, ...
        params.gapPositions);

% ============================================================
% UNKNOWN GEOMETRY
% ============================================================
else

    error( ...
        'Unknown metamaterial geometry type: %s', ...
        params.type);

end

end