function rings = generateSquareSRR( ...
    W, L, numRings, spacing, thickness, gap, gapPositions)
%GENERATESQUARESRR Generate concentric rectangular Split Ring Resonators.
%
%   rings = generateSquareSRR( ...
%       W, L, numRings, spacing, thickness, gap, gapPositions)
%
%   INPUTS
%   --------------------------------------------------------------
%   W            : Outer width of largest ring [mm]
%   L            : Outer height/length of largest ring [mm]
%   numRings     : Number of concentric rings
%   spacing      : Clear spacing between adjacent rings [mm]
%   thickness    : Metal trace width [mm]
%   gap          : Physical split width [mm]
%   gapPositions : Cell array containing one position per ring:
%
%                  {'right','left','top','bottom', ...}
%
%   Example:
%
%       gapPositions = {'right','left','top'};
%
%   means:
%
%       Ring 1 -> right
%       Ring 2 -> left
%       Ring 3 -> top
%
%   OUTPUT
%   --------------------------------------------------------------
%   rings{k}.outerX
%   rings{k}.outerY
%   rings{k}.innerX
%   rings{k}.innerY
%
%   Additional metadata:
%
%   rings{k}.W
%   rings{k}.L
%   rings{k}.gap
%   rings{k}.gapPosition
%   rings{k}.thickness


    % ============================================================
    % VALIDATE BASIC PARAMETERS
    % ============================================================
    validateattributes(W, ...
        {'numeric'}, ...
        {'scalar','real','finite','positive'});

    validateattributes(L, ...
        {'numeric'}, ...
        {'scalar','real','finite','positive'});

    validateattributes(numRings, ...
        {'numeric'}, ...
        {'scalar','real','finite','integer','positive'});

    validateattributes(spacing, ...
        {'numeric'}, ...
        {'scalar','real','finite','nonnegative'});

    validateattributes(thickness, ...
        {'numeric'}, ...
        {'scalar','real','finite','positive'});

    validateattributes(gap, ...
        {'numeric'}, ...
        {'scalar','real','finite','positive'});


    % ============================================================
    % GAP POSITIONS
    % ============================================================
    if nargin < 7 || isempty(gapPositions)

        gapPositions = ...
            repmat({'right'},1,numRings);
    end


    % Convert string array to cell array if necessary
    if isstring(gapPositions)

        gapPositions = ...
            cellstr(gapPositions);
    end


    % Single character/string -> apply to all rings
    if ischar(gapPositions)

        gapPositions = ...
            repmat({gapPositions},1,numRings);
    end


    % ============================================================
    % CHECK NUMBER OF POSITIONS
    % ============================================================
    if length(gapPositions) < numRings

        error( ...
            ['A split position must be defined for every ring. ', ...
             'Expected %d positions but received %d.'], ...
            numRings, ...
            length(gapPositions));
    end


    % ============================================================
    % VALID POSITIONS
    % ============================================================
    validPositions = { ...
        'right', ...
        'top', ...
        'left', ...
        'bottom'};


    for k = 1:numRings

        gapPositions{k} = ...
            lower(char(gapPositions{k}));

        if ~ismember( ...
                gapPositions{k}, ...
                validPositions)

            error( ...
                ['Invalid gap position for ring %d. ', ...
                 'Use right, top, left, or bottom.'], ...
                k);
        end
    end


    % ============================================================
    % BASIC DIMENSION CHECK
    % ============================================================
    if W <= 2*thickness

        error( ...
            'W must be greater than 2*thickness.');
    end


    if L <= 2*thickness

        error( ...
            'L must be greater than 2*thickness.');
    end


    % ============================================================
    % RING PITCH
    %
    % spacing = clear dielectric separation between rings
    %
    % pitch = metal width + clear spacing
    % ============================================================
    pitch = ...
        thickness + spacing;


    rings = {};


    % ============================================================
    % GENERATE EACH RING
    % ============================================================
    for k = 1:numRings

        % ========================================================
        % CURRENT RING SIZE
        % ========================================================
        Wk = ...
            W - 2*(k-1)*pitch;

        Lk = ...
            L - 2*(k-1)*pitch;


        % ========================================================
        % CHECK IF CURRENT RING FITS
        % ========================================================
        if Wk <= 2*thickness || ...
           Lk <= 2*thickness

            warning( ...
                ['Requested %d rings, but only %d rings fit ', ...
                 'inside the specified geometry.'], ...
                numRings, ...
                k-1);

            break;
        end


        % ========================================================
        % SPLIT POSITION FOR THIS SPECIFIC RING
        % ========================================================
        currentPosition = ...
            gapPositions{k};


        % ========================================================
        % CHECK GAP SIZE FOR CURRENT RING
        % ========================================================
        if ismember( ...
                currentPosition, ...
                {'top','bottom'})

            availableLength = ...
                Wk - 2*thickness;

        else

            availableLength = ...
                Lk - 2*thickness;
        end


        if gap >= availableLength

            warning( ...
                ['Ring %d cannot be generated because ', ...
                 'gap %.4f mm is too large.'], ...
                k, ...
                gap);

            break;
        end


        % ========================================================
        % GENERATE INDIVIDUAL SRR
        % ========================================================
        [outerX,outerY,innerX,innerY] = ...
            generateOneRectangularSRR( ...
                Wk, ...
                Lk, ...
                thickness, ...
                gap, ...
                currentPosition);


        % ========================================================
        % STORE RING
        % ========================================================
        rings{end+1} = struct( ...
            'outerX',outerX, ...
            'outerY',outerY, ...
            'innerX',innerX, ...
            'innerY',innerY, ...
            'W',Wk, ...
            'L',Lk, ...
            'thickness',thickness, ...
            'gap',gap, ...
            'gapPosition',currentPosition);
    end

end


% ========================================================================
% GENERATE ONE RECTANGULAR SRR
% ========================================================================
function [outerX,outerY,innerX,innerY] = ...
    generateOneRectangularSRR( ...
        W,L,thickness,gap,gapPosition)


    % ============================================================
    % HALF DIMENSIONS
    % ============================================================
    hxO = W/2;
    hyO = L/2;

    hxI = hxO - thickness;
    hyI = hyO - thickness;

    g = gap/2;


    % ============================================================
    % RIGHT SPLIT
    % ============================================================
    switch lower(gapPosition)

        case 'right'

            outerX = [ ...
                 hxO, ...
                 hxO, ...
                -hxO, ...
                -hxO, ...
                 hxO, ...
                 hxO, ...
                 hxI, ...
                 hxI, ...
                -hxI, ...
                -hxI, ...
                 hxI, ...
                 hxI, ...
                 hxO];

            outerY = [ ...
                 g, ...
                 hyO, ...
                 hyO, ...
                -hyO, ...
                -hyO, ...
                -g, ...
                -g, ...
                -hyI, ...
                -hyI, ...
                 hyI, ...
                 hyI, ...
                 g, ...
                 g];


        % ========================================================
        % TOP SPLIT
        % ========================================================
        case 'top'

            outerX = [ ...
                -g, ...
                -hxO, ...
                -hxO, ...
                 hxO, ...
                 hxO, ...
                 g, ...
                 g, ...
                 hxI, ...
                 hxI, ...
                -hxI, ...
                -hxI, ...
                -g, ...
                -g];

            outerY = [ ...
                 hyO, ...
                 hyO, ...
                -hyO, ...
                -hyO, ...
                 hyO, ...
                 hyO, ...
                 hyI, ...
                 hyI, ...
                -hyI, ...
                -hyI, ...
                 hyI, ...
                 hyI, ...
                 hyO];


        % ========================================================
        % LEFT SPLIT
        % ========================================================
        case 'left'

            outerX = [ ...
                -hxO, ...
                -hxO, ...
                 hxO, ...
                 hxO, ...
                -hxO, ...
                -hxO, ...
                -hxI, ...
                -hxI, ...
                 hxI, ...
                 hxI, ...
                -hxI, ...
                -hxI, ...
                -hxO];

            outerY = [ ...
                -g, ...
                -hyO, ...
                -hyO, ...
                 hyO, ...
                 hyO, ...
                 g, ...
                 g, ...
                 hyI, ...
                 hyI, ...
                -hyI, ...
                -hyI, ...
                -g, ...
                -g];


        % ========================================================
        % BOTTOM SPLIT
        % ========================================================
        case 'bottom'

            outerX = [ ...
                 g, ...
                 hxO, ...
                 hxO, ...
                -hxO, ...
                -hxO, ...
                -g, ...
                -g, ...
                -hxI, ...
                -hxI, ...
                 hxI, ...
                 hxI, ...
                 g, ...
                 g];

            outerY = [ ...
                -hyO, ...
                -hyO, ...
                 hyO, ...
                 hyO, ...
                -hyO, ...
                -hyO, ...
                -hyI, ...
                -hyI, ...
                 hyI, ...
                 hyI, ...
                -hyI, ...
                -hyI, ...
                -hyO];

    end


    % ============================================================
    % SINGLE CLOSED CONDUCTOR POLYGON REPRESENTATION
    % ============================================================
    innerX = [];
    innerY = [];

end