function [outerX,outerY,innerX,innerY] = ...
    generateSquareSRR( ...
    side, ...
    thickness, ...
    gap)

    % ============================================================
    % HALF DIMENSIONS
    % ============================================================
    sOuter = side/2;

    sInner = sOuter - thickness;

    % ============================================================
    % GAP SIZE
    % ============================================================
    gapSize = gap;

    % ============================================================
    % OUTER SQUARE
    % ============================================================
    outerX = [ ...
        -sOuter ...
         sOuter ...
         sOuter ...
        -sOuter ...
        -sOuter];

    outerY = [ ...
        -sOuter ...
        -sOuter ...
         sOuter ...
         sOuter ...
        -sOuter];

    % ============================================================
    % INNER SQUARE
    % ============================================================
    innerX = [ ...
        -sInner ...
         sInner ...
         sInner ...
        -sInner ...
        -sInner];

    innerY = [ ...
        -sInner ...
        -sInner ...
         sInner ...
         sInner ...
        -sInner];

    % ============================================================
    % CREATE SPLIT GAP
    % ============================================================
    %
    % Gap located on right side
    %
    % Remove segment from both contours
    %
    % ============================================================

    % Outer contour gap
    outerX = [ ...
        -sOuter ...
         sOuter ...
         sOuter ...
         sOuter-gapSize ...
        -sOuter ...
        -sOuter];

    outerY = [ ...
        -sOuter ...
        -sOuter ...
         gapSize ...
         sOuter ...
         sOuter ...
        -sOuter];

    % Inner contour gap
    innerX = [ ...
        -sInner ...
         sInner ...
         sInner ...
         sInner-gapSize ...
        -sInner ...
        -sInner];

    innerY = [ ...
        -sInner ...
        -sInner ...
         gapSize ...
         sInner ...
         sInner ...
        -sInner];

    % ============================================================
    % ENSURE CLOSED POLYGONS
    % ============================================================
    if outerX(1) ~= outerX(end) || ...
       outerY(1) ~= outerY(end)

        outerX(end+1) = outerX(1);
        outerY(end+1) = outerY(1);
    end

    if innerX(1) ~= innerX(end) || ...
       innerY(1) ~= innerY(end)

        innerX(end+1) = innerX(1);
        innerY(end+1) = innerY(1);
    end
end