function s1 = srrLcModel(geom, params)
%SRRLCMODEL  Stage 1 - quasi-static equivalent-circuit L, C and f0 of an
%            SRR / CSRR inclusion generated by BUILDMETAMATERIAL.
%
%   s1 = srrLcModel(geom, params)
%
%   INPUTS
%     geom   - cell array of ring structs (BUILDMETAMATERIAL output) or a
%              single ring struct. Coordinates are in millimetres.
%     params - GUI parameter struct. Fields used:
%                .type        'gielis' | 'ssrr'
%                .mode        'SRR' | 'CSRR'
%                .thickness   metal trace width  [mm]
%                .spacing     edge-to-edge ring separation [mm]
%                .splitGap    split-gap width    [mm]   (falls back to .gapSSRR)
%                .substrateThickness [mm]
%                .dielectricMaterial (name) or .substrate_er (numeric)
%
%   OUTPUT struct s1
%     .L, .C      effective lumped inductance / capacitance [H], [F]
%     .f0         predicted resonance [Hz]
%     .shape      'circular' | 'square'
%     .n          number of rings
%     .r0         mean ring radius [m]
%     .Cpul       inter-ring capacitance per unit length [F/m]
%     .C0         total inter-ring capacitance [F]
%     .Cgap       split-gap capacitance [F]
%     .Lgeom,.Cgeom  the geometric (SRR-sense) values before any Babinet swap
%     .er, .er_eff
%
%   Method: Marques/Baena EC-SRR (C0 = perimeter*Cpul, Cs = C0/4) with the
%   Mohan/Bilotti current-sheet inductance (RINGINDUCTANCE). CSRR uses the
%   Babinet swap L<->C with the substrate-scaled er_eff; note that ideal
%   Babinet duality leaves f0 unchanged - the SRR/CSRR distinction is carried
%   by Stage 2 (magnetic vs electric Lorentzian response).
%
%   See also RINGINDUCTANCE, COPLANARSTRIPCPUL, RUNANALYTICALPIPELINE.

    eps0 = 8.8541878128e-12;
    mu0  = 1.25663706212e-6;

    if ~iscell(geom); geom = {geom}; end
    n = numel(geom);

    % ---- material -----------------------------------------------------
    if isfield(params, 'substrate_er') && ~isempty(params.substrate_er)
        er = params.substrate_er;
    elseif isfield(params, 'dielectricMaterial')
        er = substratePermittivity(params.dielectricMaterial);
    else
        er = 4.3;
    end
    h = getfielddef(params, 'substrateThickness', 1.6) * 1e-3;

    % ---- geometry (mm -> m) ------------------------------------------
    c = getfielddef(params, 'thickness', 0.15) * 1e-3;      % trace width
    d = getfielddef(params, 'spacing',   0.20) * 1e-3;      % ring separation
    g = getfielddef(params, 'splitGap', ...
            getfielddef(params, 'gapSSRR', 0.30)) * 1e-3;   % split gap
    g = max(g, 1e-6);

    isSquare = strcmpi(getfielddef(params, 'type', 'gielis'), 'ssrr');
    shape    = ternary(isSquare, 'square', 'circular');

    % outer boundary of the outermost ring, inner boundary of the innermost.
    % geom coordinates are in millimetres -> convert to metres.
    [rOuter, pOuter] = ringExtent(geom{1},   'outer');
    [rInner, pInner] = ringExtent(geom{end}, 'inner');
    rOuter = rOuter * 1e-3;  pOuter = pOuter * 1e-3;
    rInner = rInner * 1e-3;  pInner = pInner * 1e-3;
    if rInner >= rOuter || ~isfinite(rInner)
        rInner = max(rOuter - n*(2*c + d), 0.25*rOuter);
    end

    r0    = 0.5 * (rOuter + rInner);
    dAvg  = (rOuter + rInner);                 % average loop diameter
    rho   = (rOuter - rInner) / (rOuter + rInner);

    % actual footprint of the outermost ring (m^2) for the filling factor
    fw = (max(geom{1}.outerX) - min(geom{1}.outerX)) * 1e-3;
    fh = (max(geom{1}.outerY) - min(geom{1}.outerY)) * 1e-3;
    footprint = fw * fh;
    if ~isfinite(footprint) || footprint <= 0
        footprint = pi * rOuter^2;
    end
    p0    = 0.5 * (pOuter + pInner);           % mean-ring perimeter
    if ~isfinite(p0) || p0 <= 0
        p0 = ternary(isSquare, 8*r0, 2*pi*r0);
    end

    % ---- capacitance ----------------------------------------------
    % An N-ring (M)SRR has (N-1) concentric coupling regions; a lone split
    % ring couples through its own gap only. Marques/Bilotti: Cs = C0/4 with
    % C0 the distributed inter-ring capacitance summed over the coupled pairs.
    tMetal = getfielddef(params, 'metalThickness', 35e-6);    % copper cladding
    nPairs = max(n - 1, 1);
    [Cpul, er_eff] = coplanarStripCpul(c, d, er, h);
    C0   = nPairs * p0 * Cpul;                 % total inter-ring capacitance
    % split-gap: parallel-plate across the trace cross-section + edge fringe
    Cgap = eps0 * er_eff * (c * tMetal / g) + eps0 * er_eff * (c + tMetal);
    Cgeom = C0/4 + Cgap;                       % SRR series capacitance

    % ---- inductance ----------------------------------------------
    % EC-SRR / MSRR inductance is that of the single equivalent loop at the
    % average radius (the miniaturisation of an MSRR comes from the added
    % capacitance, not an n^2 inductance - that applies only to galvanically
    % connected spirals).
    Lgeom = ringInductance(dAvg, rho, 1, shape);

    % ---- SRR / CSRR --------------------------------------------------
    if strcmpi(getfielddef(params, 'mode', 'SRR'), 'CSRR')
        % Babinet swap: L <-> C with eta_eff^2 = mu0 / (4*eps0*er_eff)
        C = Lgeom * (4 * eps0 * er_eff / mu0);
        L = Cgeom * (mu0 / (4 * eps0 * er_eff));
    else
        L = Lgeom;
        C = Cgeom;
    end

    f0 = 1 / (2*pi*sqrt(L * C));

    % ---- pack -------------------------------------------------------
    s1 = struct('L', L, 'C', C, 'f0', f0, 'shape', shape, 'n', n, ...
                'r0', r0, 'rOuter', rOuter, 'rInner', rInner, 'rho', rho, ...
                'perimeter', p0, 'footprint', footprint, ...
                'Cpul', Cpul, 'C0', C0, 'Cgap', Cgap, ...
                'Lgeom', Lgeom, 'Cgeom', Cgeom, 'er', er, 'er_eff', er_eff, ...
                'mode', upper(getfielddef(params, 'mode', 'SRR')));
end

% ======================================================================
function [r, p] = ringExtent(ring, which)
%RINGEXTENT  Max/min radius from centroid and perimeter of a ring contour.
    switch which
        case 'outer'
            x = ring.outerX(:); y = ring.outerY(:);
        otherwise
            if isfield(ring, 'innerX') && ~isempty(ring.innerX)
                x = ring.innerX(:); y = ring.innerY(:);
            else            % single-polygon ribbon: use its own outline
                x = ring.outerX(:); y = ring.outerY(:);
            end
    end

    if isempty(x); r = NaN; p = NaN; return; end

    m  = polygonMetrics(x, y);
    cx = mean(x); cy = mean(y);
    rr = hypot(x - cx, y - cy);

    if strcmp(which, 'outer')
        r = max(rr);
    else
        r = min(rr);
    end
    p = m.perimeter;
end

% ----------------------------------------------------------------------
function v = getfielddef(s, f, d)
    if isfield(s, f) && ~isempty(s.(f)); v = s.(f); else; v = d; end
end

function out = ternary(cond, a, b)
    if cond; out = a; else; out = b; end
end
